# Goreleaser configuration: http://goreleaser.com
before:
  hooks:
  - make npm-install
  - make fe
builds:
  -
    env:
    - GO111MODULE=off
    - CGO_ENABLED=0
    - GOPATH=/Users/runner/work/web-embed-lab/web-embed-lab/go
    id: "runner"
    binary: "runner"
    main: ./go/src/wel/commands/runner/main/runner.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    hooks:
      post: make bintarget={{ .Path }} sign
  -
    env:
    - CGO_ENABLED=0
    - GOPATH=/Users/runner/work/web-embed-lab/web-embed-lab/go
    id: "auto-formulate"
    binary: "auto-formulate"
    main: ./go/src/wel/commands/auto-formulate/main/auto-formulate.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    hooks:
      post: make bintarget={{ .Path }} sign

archives:
  -
    builds:
    - "runner"
    - "auto-formulate" 

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: fullstorydev
    name: web-embed-lab
